### ISSUE TITLE
OrphanedResources.MD :: Query is invalid.

### ISSUE THREAD

**Issue by francesco1119** [scautomation/AzureResourceGraph-Examples#2]
While trying to use the "_Find unused Web API connections - Credit Mohammed Barqawi_" I discovered that the query returns this error: 

```
Please provide below info when asking for support: timestamp = 2022-08-22T10:38:25.4583215Z, correlationId = 7813bc9e-xxxx-xxxx-xxxx-d8a787c38b29. (Code:BadRequest)

Details:
Query is invalid. Please refer to the documentation for the Azure Resource Graph service and fix the error before retrying. (Code:InvalidQuery)
ParserFailure (Code:ParserFailure)
ParserFailure (Code:ParserFailure)
ParserFailure (Code:ParserFailure)
More information on the error can be found [here](https://portal.azure.com/#).
```

**Comment by francesco1119** [comment]
Probably the right query is [here](https://techcommunity.microsoft.com/t5/integrations-on-azure-blog/find-orphans-unused-web-api-connection-and-gateway-name-using/ba-p/2465200); it is provided by  Mohammed Barqawi

**Comment by scautomation** [comment]
the query in the repo is directly copied from Mohammed, as noted in the notes.
