### ISSUE TITLE
Is there a way to get the same result from az cli powershell commands?

### ISSUE THREAD

**Issue by tuxerrante** [scautomation/AzureResourceGraph-Examples#6]
Hi,
I'd like to automate your queries in an Azure pipeline.
I've found something very simple like this  
`az disk list --query '[?managedBy==`null`].[id]' -o tsv`
that I could iterate over all resources, 
or [this](https://www.controlup.com/script-library-posts/az-find-potentially-orphaned-azure-resources/) overcomplicated script.

I've found the [resource graph REST APIs](https://learn.microsoft.com/en-us/rest/api/azureresourcegraph/resourcegraph(2021-03-01)/resources), but there is also a way to run them trhough simpler, self contained az cli commands? 
Would you consider publishing also that?

Thanks

**Comment by scautomation** [comment]
I have not tried through Azure CLI. If I can find the time I will try to create CLI examples. Is there anything specific you'd like to try, aside from the disk example you gave.

**Comment by tuxerrante** [comment]
I'd like to list all major resources left as orphans or not used anymore in our cloud, anything costly is a good start :)

I'm using this right now but there is the issue that [managedBy](https://learn.microsoft.com/en-us/rest/api/resources/resources/list#genericresourceexpanded) field is often not used by the resources so I'm getting a lot of false positives

```
resources=("vm" "disk" "keyvault" "acr" "network vnet" "network nic" "network public-ip")
for str in "${resources[@]}"; do
  echo "> $str:" | tee -a resources.log
  az ${str} list --query '[?managedBy==`null`].[id]' -o tsv | tee -a resources.log
done
```

**Comment by scautomation** [comment]
yea its not consistent cause each resource provider implements their stuff differently, rather frustrating to be honest. adding to my virtual backlog. If you find some good examples or make your own in the meantime feel free to do a pull request.
